/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:02237d53-7c8f-4df5-a9f4-e4c6b7d388d5",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Q1HPcptOe",
    "aws_user_pools_web_client_id": "5iv4s9g6ja6ubjeudtme8u10p1",
    "oauth": {}
};


export default awsmobile;
